# PCDA | Winter 2026 
### Final Project - Motor Vehicle Collisions Crashes
### Author: Bipika Sapkota & Pooja Mengaji 
### Data cleaning

Importing the dataset into the Jupyter Notebook using pandas.

In [35]:
import pandas as pd

df = pd.read_csv("data/Motor_Vehicle_Collisions_Crashes.csv")
df.head()

,CRASH DATE,CRASH TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,09/11/2021,2:39,NaN,NaN,NaN,NaN,NaN,WHITESTONE EXPRESSWAY,20 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4455765,Sedan,Sedan,NaN,NaN,NaN
1,03/26/2022,11:45,NaN,NaN,NaN,NaN,NaN,QUEENSBORO BRIDGE UPPER,NaN,NaN,...,NaN,NaN,NaN,NaN,4513547,Sedan,NaN,NaN,NaN,NaN
2,11/01/2023,1:29,BROOKLYN,11230.0,40.62179,-73.970024,"(40.62179, -73.970024)",OCEAN PARKWAY,AVENUE K,NaN,...,Unspecified,Unspecified,NaN,NaN,4675373,Moped,Sedan,Sedan,NaN,NaN
3,06/29/2022,6:55,NaN,NaN,NaN,NaN,NaN,THROGS NECK BRIDGE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4541903,Sedan,Pick-up Truck,NaN,NaN,NaN
4,09/21/2022,13:21,NaN,NaN,NaN,NaN,NaN,BROOKLYN BRIDGE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4566131,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN

Examining data structure by checking the number of rows and columns, column names, and data types. This helps us understand the dataset and identify any missing values or inconsistencies that needs to be addressed.

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 29 columns):
 #   Column                         Non-Null Count    Dtype
---  ------                         --------------    -----
 0   CRASH DATE                     1048575 non-null  str
 1   CRASH TIME                     1048575 non-null  str
 2   BOROUGH                        680750 non-null   str
 3   ZIP CODE                       680576 non-null   float64
 4   LATITUDE                       970365 non-null   float64
 5   LONGITUDE                      970365 non-null   float64
 6   LOCATION                       970365 non-null   str
 7   ON STREET NAME                 782651 non-null   str
 8   CROSS STREET NAME              504057 non-null   str
 9   OFF STREET NAME                264811 non-null   str
 10  NUMBER OF PERSONS INJURED      1048562 non-null  float64
 11  NUMBER OF PERSONS KILLED       1048555 non-null  float64
 12  NUMBER OF PEDESTRIANS INJURED  1048575 non-null  int64
 13  NUMBER OF PEDESTRIANS KILLED   1048575 non-null  int64
 14  NUMBER OF CYCLIST INJURED      1048575 non-null  int64
 15  NUMBER OF CYCLIST KILLED       1048575 non-null  int64
 16  NUMBER OF MOTORIST INJURED     1048575 non-null  int64
 17  NUMBER OF MOTORIST KILLED      1048575 non-null  int64
 18  CONTRIBUTING FACTOR VEHICLE 1  1044099 non-null  str
 19  CONTRIBUTING FACTOR VEHICLE 2  853898 non-null   str
 20  CONTRIBUTING FACTOR VEHICLE 3  82643 non-null    str
 21  CONTRIBUTING FACTOR VEHICLE 4  19976 non-null    str
 22  CONTRIBUTING FACTOR VEHICLE 5  5725 non-null     str
 23  COLLISION_ID                   1048575 non-null  int64
 24  VEHICLE TYPE CODE 1            1038842 non-null  str
 25  VEHICLE TYPE CODE 2            775715 non-null   str
 26  VEHICLE TYPE CODE 3            77818 non-null    str
 27  VEHICLE TYPE CODE 4            19034 non-null    str
 28  VEHICLE TYPE CODE 5            5514 non-null     str
dtypes: float64(5), int64(7), str(17)
memory usage: 371.1 MB

Since there are so many variables that we will not be using for this project, we are selecting only the variables that are relevant to our analysis, as it reduces the complexity.

In [37]:
columns_to_keep = [
    "CRASH DATE",
    "CRASH TIME",
    "BOROUGH",
    "ZIP CODE",
    "LATITUDE",
    "LONGITUDE",
    "NUMBER OF PERSONS INJURED",
    "NUMBER OF PERSONS KILLED",
    "NUMBER OF PEDESTRIANS INJURED",
    "NUMBER OF CYCLIST INJURED",
    "NUMBER OF MOTORIST INJURED",
    "CONTRIBUTING FACTOR VEHICLE 1",
    "VEHICLE TYPE CODE 1",
    "COLLISION_ID"
]

df = df[columns_to_keep]

In [38]:
df.isnull().sum()

CRASH DATE                            0
CRASH TIME                            0
BOROUGH                          367825
ZIP CODE                         367999
LATITUDE                          78210
LONGITUDE                         78210
NUMBER OF PERSONS INJURED            13
NUMBER OF PERSONS KILLED             20
NUMBER OF PEDESTRIANS INJURED         0
NUMBER OF CYCLIST INJURED             0
NUMBER OF MOTORIST INJURED            0
CONTRIBUTING FACTOR VEHICLE 1      4476
VEHICLE TYPE CODE 1                9733
COLLISION_ID                          0
dtype: int64

Handeling the missing vlaues

In [39]:
df["BOROUGH"] = df["BOROUGH"].fillna("Unknown")

injury_cols = [
    "NUMBER OF PERSONS INJURED",
    "NUMBER OF PERSONS KILLED",
    "NUMBER OF PEDESTRIANS INJURED",
    "NUMBER OF CYCLIST INJURED",
    "NUMBER OF MOTORIST INJURED"
]

df[injury_cols] = df[injury_cols].fillna(0)

df["CONTRIBUTING FACTOR VEHICLE 1"] = df["CONTRIBUTING FACTOR VEHICLE 1"].fillna("Unspecified")
df["VEHICLE TYPE CODE 1"] = df["VEHICLE TYPE CODE 1"].fillna("Unknown")

We notice that a large portion of the dataset has missing values for both borough and zip code, and these two fields are missing together in most cases. Since this represents a significant part of the data, we decide not to remove those rows in order to avoid losing a large amount of information. Instead, we replaced the missing borough values with "Unknown" so that these records can still be included in the analysis, especially for time-based patterns and injury-related insights. We keep the zip code values as missing since they are not essential for the main analysis.

Missing values in injury-related columns are replaced with 0, assuming no reported injuries. Missing values in contributing factors and vehicle type columns are replaced with "Unspecified" and "Unknown" respectively. This allows us to preserve as much data as possible without removing important records.

In [40]:
df["CRASH DATE"] = pd.to_datetime(df["CRASH DATE"])
df["CRASH TIME"] = pd.to_datetime(df["CRASH TIME"], format="%H:%M", errors="coerce")

In [41]:
df["HOUR"] = df["CRASH TIME"].dt.hour
df["YEAR"] = df["CRASH DATE"].dt.year
df["MONTH"] = df["CRASH DATE"].dt.month_name()
df["DAY"] = df["CRASH DATE"].dt.day
df["DAY_OF_WEEK"] = df["CRASH DATE"].dt.day_name()

In [42]:
df[["CRASH DATE", "CRASH TIME", "YEAR", "MONTH", "DAY", "DAY_OF_WEEK", "HOUR"]].head()

  CRASH DATE          CRASH TIME  YEAR      MONTH  DAY DAY_OF_WEEK  HOUR
0 2021-09-11 1900-01-01 02:39:00  2021  September   11    Saturday     2
1 2022-03-26 1900-01-01 11:45:00  2022      March   26    Saturday    11
2 2023-11-01 1900-01-01 01:29:00  2023   November    1   Wednesday     1
3 2022-06-29 1900-01-01 06:55:00  2022       June   29   Wednesday     6
4 2022-09-21 1900-01-01 13:21:00  2022  September   21   Wednesday    13

In [43]:
df.isnull().sum()

CRASH DATE                            0
CRASH TIME                            0
BOROUGH                               0
ZIP CODE                         367999
LATITUDE                          78210
LONGITUDE                         78210
NUMBER OF PERSONS INJURED             0
NUMBER OF PERSONS KILLED              0
NUMBER OF PEDESTRIANS INJURED         0
NUMBER OF CYCLIST INJURED             0
NUMBER OF MOTORIST INJURED            0
CONTRIBUTING FACTOR VEHICLE 1         0
VEHICLE TYPE CODE 1                   0
COLLISION_ID                          0
HOUR                                  0
YEAR                                  0
MONTH                                 0
DAY                                   0
DAY_OF_WEEK                           0
dtype: int64

Renaming the columns for better vizualizations

In [47]:
df = df.rename(columns={
    "CRASH DATE": "CRASH DATE", #"crash_date",
    "CRASH TIME": "CRASH TIME", #"crash_time",
    "BOROUGH": "BOROUGH",
    "ZIP CODE": "ZIP CODE", #"zip_code",
    "LATITUDE": "LATITUDE",
    "LONGITUDE": "LONGITUDE",
    "NUMBER OF PERSONS INJURED":  "NUMBER OF PERSONS INJURED", # "persons_injured",
    "NUMBER OF PERSONS KILLED": "NUMBER OF PERSONS KILLED", #"persons_killed",
    "NUMBER OF PEDESTRIANS INJURED": "NUMBER OF PEDESTRIANS INJURED", #"pedestrians_injured",
    "NUMBER OF CYCLIST INJURED": "NUMBER OF CYCLIST INJURED", #"cyclists_injured",
    "NUMBER OF MOTORIST INJURED": "NUMBER OF MOTORIST INJURED", #"motorists_injured",
     "CONTRIBUTING FACTOR VEHICLE 1": "CONTRIBUTING FACTOR",
     "VEHICLE TYPE CODE 1": "VEHICLE TYPE",
    "COLLISION_ID": "COLLISION_ID"
 })

In [48]:
df.to_csv("data/Cleaned_Motor_Vehicle_Collisions_Crashes.csv", index=False)